#!/bin/bash
# ##########################################################
# ALPS(Android4.1 based) build environment profile setting
# ##########################################################
# Overwrite JAVA_HOME environment variable setting if already exists
perl syscLtk $1 $2;
LTK_SYSNC=`cat LTK_SYSNC`;
LTK_LUNCH=`cat LTK_LUNCH`;

if [ "$LTK_SYSNC" = "success" ]
then
source build/envsetup.sh
if [ "$LTK_LUNCH" = "eng" ]
then
echo eng
lunch full_hexing6580_we_m-eng
else
echo user
lunch full_hexing6580_we_m-user
fi
else
echo failure
fi
